//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Languages.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circles.
        /// </summary>
        internal static string Circles {
            get {
                return ResourceManager.GetString("Circles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Empty list of shapes!&lt;/h1&gt;.
        /// </summary>
        internal static string EmptyListMsg {
            get {
                return ResourceManager.GetString("EmptyListMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equilateral Triangle.
        /// </summary>
        internal static string EquilateralTriangle {
            get {
                return ResourceManager.GetString("EquilateralTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equilateral Triangles.
        /// </summary>
        internal static string EquilateralTriangles {
            get {
                return ResourceManager.GetString("EquilateralTriangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Shapes report&lt;/h1&gt;.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter.
        /// </summary>
        internal static string Perimeter {
            get {
                return ResourceManager.GetString("Perimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shape.
        /// </summary>
        internal static string shape {
            get {
                return ResourceManager.GetString("shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shapes.
        /// </summary>
        internal static string shapes {
            get {
                return ResourceManager.GetString("shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squares.
        /// </summary>
        internal static string Squares {
            get {
                return ResourceManager.GetString("Squares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL:&lt;br/&gt;.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
